requires 'EV' => '4.18';
requires 'HTML::StripScripts::Parser';
requires 'IO::Socket::IP'         => '0.36';
requires 'IO::Socket::SSL'        => '2.009';
requires 'IPC::Run'               => '0.92';
requires 'Mango'                  => '1.14';
requires 'Minion'                 => '1.05';
requires 'Minion::Backend::Mango' => '0.92';
requires 'Mojolicious'            => '5.74';
requires 'Text::Markdown';
requires 'XML::RSS';
