#!/usr/bin/perl -l

use warnings;

use IPC::Run qw/run timeout/;
use JSON::PP 'encode_json';

my $interpret = shift // '/usr/bin/perl';
my @args      = @ARGV;
my $dir       = '/opt/share/';
my $timeout   = 10;
my $code      = './code';
my $input     = './input';

binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

chdir $dir;

open my $in, '<', $input or do {
  print encode_json {status => 'fail', stderr => "Can't open input file: $!"};
  exit;
};

my @cmd;
if (@args) {
  @cmd = ($interpret, @args, $code);
} else {
  @cmd = ($interpret, @args ? (@args, $code) : $code);
}

my ($out, $err) = (undef, undef);
my $res = eval { run \@cmd, $in, \$out, \$err, timeout($timeout); };
close $in;

my $status = $@ ? 'fail' : $res ? 'ok' : 'error';
my $result = {status => $status, stderr => $status eq 'fail' ? $@ : $err, stdout => $out};
print JSON::PP->new->encode($result);
